#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kata-shim
Version  : 1.6.0
Release  : 16
URL      : https://github.com/kata-containers/shim/archive/1.6.0.tar.gz
Source0  : https://github.com/kata-containers/shim/archive/1.6.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause GPL-2.0 ISC MIT MPL-2.0-no-copyleft-exception
Requires: kata-shim-libexec = %{version}-%{release}
Requires: kata-shim-license = %{version}-%{release}
BuildRequires : buildreq-golang
Patch1: 0001-add-fake-autogen.patch

%description
[![Build Status](https://travis-ci.org/kata-containers/shim.svg?branch=master)](https://travis-ci.org/kata-containers/shim)
[![codecov](https://codecov.io/gh/kata-containers/shim/branch/master/graph/badge.svg)](https://codecov.io/gh/kata-containers/shim)

%package libexec
Summary: libexec components for the kata-shim package.
Group: Default
Requires: kata-shim-license = %{version}-%{release}

%description libexec
libexec components for the kata-shim package.


%package license
Summary: license components for the kata-shim package.
Group: Default

%description license
license components for the kata-shim package.


%prep
%setup -q -n shim-1.6.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1553643157
export LDFLAGS="${LDFLAGS} -fno-lto"
%autogen --disable-static ;export GOPATH="${PWD}/gopath/" \
;mkdir -p "${GOPATH}/src/github.com/kata-containers/" \
;ln -sf "${PWD}" "${GOPATH}/src/github.com/kata-containers/shim" \
;cd "${GOPATH}/src/github.com/kata-containers/shim"
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1553643157
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kata-shim
cp LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/LICENSE
cp vendor/github.com/Azure/go-ansiterm/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_Azure_go-ansiterm_LICENSE
cp vendor/github.com/codahale/hdrhistogram/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_codahale_hdrhistogram_LICENSE
cp vendor/github.com/davecgh/go-spew/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_davecgh_go-spew_LICENSE
cp vendor/github.com/docker/docker/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_docker_docker_LICENSE
cp vendor/github.com/docker/docker/NOTICE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_docker_docker_NOTICE
cp vendor/github.com/docker/docker/contrib/selinux-fedora-24/docker-engine-selinux/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_docker_docker_contrib_selinux-fedora-24_docker-engine-selinux_LICENSE
cp vendor/github.com/docker/docker/contrib/selinux-oraclelinux-7/docker-engine-selinux/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_docker_docker_contrib_selinux-oraclelinux-7_docker-engine-selinux_LICENSE
cp vendor/github.com/docker/docker/contrib/syntax/vim/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_docker_docker_contrib_syntax_vim_LICENSE
cp vendor/github.com/docker/docker/pkg/symlink/LICENSE.APACHE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_docker_docker_pkg_symlink_LICENSE.APACHE
cp vendor/github.com/docker/docker/pkg/symlink/LICENSE.BSD %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_docker_docker_pkg_symlink_LICENSE.BSD
cp vendor/github.com/gogo/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_gogo_protobuf_LICENSE
cp vendor/github.com/golang/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_golang_protobuf_LICENSE
cp vendor/github.com/grpc-ecosystem/grpc-opentracing/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_grpc-ecosystem_grpc-opentracing_LICENSE
cp vendor/github.com/hashicorp/yamux/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_hashicorp_yamux_LICENSE
cp vendor/github.com/kata-containers/agent/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_kata-containers_agent_LICENSE
cp vendor/github.com/kr/pty/License %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_kr_pty_License
cp vendor/github.com/mdlayher/vsock/LICENSE.md %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_mdlayher_vsock_LICENSE.md
cp vendor/github.com/moby/moby/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_moby_moby_LICENSE
cp vendor/github.com/moby/moby/NOTICE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_moby_moby_NOTICE
cp vendor/github.com/moby/moby/contrib/selinux-fedora-24/docker-engine-selinux/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_moby_moby_contrib_selinux-fedora-24_docker-engine-selinux_LICENSE
cp vendor/github.com/moby/moby/contrib/selinux-oraclelinux-7/docker-engine-selinux/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_moby_moby_contrib_selinux-oraclelinux-7_docker-engine-selinux_LICENSE
cp vendor/github.com/moby/moby/contrib/selinux/docker-engine-selinux/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_moby_moby_contrib_selinux_docker-engine-selinux_LICENSE
cp vendor/github.com/moby/moby/contrib/syntax/vim/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_moby_moby_contrib_syntax_vim_LICENSE
cp vendor/github.com/moby/moby/pkg/symlink/LICENSE.APACHE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_moby_moby_pkg_symlink_LICENSE.APACHE
cp vendor/github.com/moby/moby/pkg/symlink/LICENSE.BSD %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_moby_moby_pkg_symlink_LICENSE.BSD
cp vendor/github.com/opencontainers/runtime-spec/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_opencontainers_runtime-spec_LICENSE
cp vendor/github.com/opentracing/opentracing-go/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_opentracing_opentracing-go_LICENSE
cp vendor/github.com/pkg/errors/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_pkg_errors_LICENSE
cp vendor/github.com/pmezard/go-difflib/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_pmezard_go-difflib_LICENSE
cp vendor/github.com/sirupsen/logrus/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_sirupsen_logrus_LICENSE
cp vendor/github.com/stretchr/testify/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_stretchr_testify_LICENSE
cp vendor/github.com/uber/jaeger-client-go/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_uber_jaeger-client-go_LICENSE
cp vendor/github.com/uber/jaeger-lib/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_github.com_uber_jaeger-lib_LICENSE
cp vendor/golang.org/x/crypto/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_golang.org_x_crypto_LICENSE
cp vendor/golang.org/x/net/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_golang.org_x_net_LICENSE
cp vendor/golang.org/x/sys/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_golang.org_x_sys_LICENSE
cp vendor/golang.org/x/text/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_golang.org_x_text_LICENSE
cp vendor/google.golang.org/genproto/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_google.golang.org_genproto_LICENSE
cp vendor/google.golang.org/grpc/LICENSE %{buildroot}/usr/share/package-licenses/kata-shim/vendor_google.golang.org_grpc_LICENSE
%make_install LIBEXECDIR=/usr/libexec/

%files
%defattr(-,root,root,-)

%files libexec
%defattr(-,root,root,-)
/usr/libexec/kata-containers/kata-shim

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kata-shim/LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_Azure_go-ansiterm_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_codahale_hdrhistogram_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_davecgh_go-spew_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_docker_docker_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_docker_docker_NOTICE
/usr/share/package-licenses/kata-shim/vendor_github.com_docker_docker_contrib_selinux-fedora-24_docker-engine-selinux_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_docker_docker_contrib_selinux-oraclelinux-7_docker-engine-selinux_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_docker_docker_contrib_syntax_vim_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_docker_docker_pkg_symlink_LICENSE.APACHE
/usr/share/package-licenses/kata-shim/vendor_github.com_docker_docker_pkg_symlink_LICENSE.BSD
/usr/share/package-licenses/kata-shim/vendor_github.com_gogo_protobuf_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_golang_protobuf_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_grpc-ecosystem_grpc-opentracing_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_hashicorp_yamux_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_kata-containers_agent_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_kr_pty_License
/usr/share/package-licenses/kata-shim/vendor_github.com_mdlayher_vsock_LICENSE.md
/usr/share/package-licenses/kata-shim/vendor_github.com_moby_moby_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_moby_moby_NOTICE
/usr/share/package-licenses/kata-shim/vendor_github.com_moby_moby_contrib_selinux-fedora-24_docker-engine-selinux_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_moby_moby_contrib_selinux-oraclelinux-7_docker-engine-selinux_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_moby_moby_contrib_selinux_docker-engine-selinux_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_moby_moby_contrib_syntax_vim_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_moby_moby_pkg_symlink_LICENSE.APACHE
/usr/share/package-licenses/kata-shim/vendor_github.com_moby_moby_pkg_symlink_LICENSE.BSD
/usr/share/package-licenses/kata-shim/vendor_github.com_opencontainers_runtime-spec_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_opentracing_opentracing-go_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_pkg_errors_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_pmezard_go-difflib_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_sirupsen_logrus_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_stretchr_testify_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_uber_jaeger-client-go_LICENSE
/usr/share/package-licenses/kata-shim/vendor_github.com_uber_jaeger-lib_LICENSE
/usr/share/package-licenses/kata-shim/vendor_golang.org_x_crypto_LICENSE
/usr/share/package-licenses/kata-shim/vendor_golang.org_x_net_LICENSE
/usr/share/package-licenses/kata-shim/vendor_golang.org_x_sys_LICENSE
/usr/share/package-licenses/kata-shim/vendor_golang.org_x_text_LICENSE
/usr/share/package-licenses/kata-shim/vendor_google.golang.org_genproto_LICENSE
/usr/share/package-licenses/kata-shim/vendor_google.golang.org_grpc_LICENSE
